# Generated by Django 4.1.7 on 2023-03-05 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='webinars',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='status',
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='webinar.teacher'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinars', to='webinar.webinar'),
        ),
    ]
