# Generated by Django 4.1.7 on 2023-03-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0004_webinar_teachers_alter_schedule_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='webinars',
            field=models.ManyToManyField(through='webinar.Schedule', to='webinar.webinar'),
        ),
    ]
